### PR TITLE
README: Fixup the tailscale commands

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by maggie44** [comment]
Do the subnet features still work without these flags?

https://tailscale.com/kb/1019/subnets/#step-3-enable-subnet-routes-from-the-admin-console

**Comment by klutchell** [comment]
> Do the subnet features still work without these flags?
> 
> https://tailscale.com/kb/1019/subnets/#step-3-enable-subnet-routes-from-the-admin-console

No, the device needs to provide the subnet flags and then they need to be approved in the dashboard. If the device does not advertise the subnets they cannot be added/approved.

**Comment by maggie44** [comment]
Oh I see it now, I thought you were removing the flags. 

LGTM, thanks.

**Review by maggie44 — APPROVED** [review]

**Comment by maggie44** [comment]
@klutchell, out of curiosity, which setup did you use to try it out? Digital Ocean, local or some other form?

**Comment by klutchell** [comment]
@maggie0002 Deployed on my Intel NUC, works great!

**Pull request merged**
